---
- name: Define acceptable distros
  set_fact:
    debian_distro: ['Debian', 'Ubuntu']
    rhel_distro: ['CentOS', 'RedHat', 'Red Hat Enterprise Linux', 'Amazon']
    windows_distro: ['Windows']
    cacheable: true

- name: Confirm agent configuration is provided
  fail: msg='Please provide a populated sfx_agent_config'
  when: not (sfx_agent_config | default(false))

- name: Confirm SignalFx Access Token is defined
  fail: msg='Please specify a signalFxAccessToken in your sfx_agent_config'
  when: not (sfx_agent_config.signalFxAccessToken | default('') | trim) or not sfx_agent_config.signalFxAccessToken

- name: Acceptable distribution check
  fail:
    msg: >
         Bailing out. This play is supported on {{ debian_distro }}, {{ rhel_distro }} and {{ windows_distro }}.
         Target server runs on {{ ansible_os_family }}.
  when: (ansible_os_family not in debian_distro)
          and
        (ansible_os_family not in rhel_distro)
          and
        (ansible_os_family not in windows_distro)

- name: Linux deployment
  include_tasks: linux_install.yml
  when: not ansible_os_family in windows_distro

- name: Windows deployment
  include_tasks: win_install.yml
  when: ansible_os_family in windows_distro
