---
- name: Add Signalfx Agent repo into source list
  yum_repository:
    name: signalfx-agent
    description: SignalFx Agent Repository
    baseurl: "{{ repo_base_url }}/rpms/signalfx-agent/{{ package_stage }}"
    gpgkey: "{{ repo_base_url }}/yum-rpm.key"
    gpgcheck: yes
    enabled: yes

- name: Install signalfx-agent via yum package manager
  yum: 
    name: signalfx-agent{% if version is defined and version != "latest" %}-{{ version }}{% endif %}
    state: "{% if version is defined and version != 'latest' %}present{% else %}{{ version }}{% endif %}"
    allow_downgrade: yes
    update_cache: yes

