---
# Deploy signalfx-agent via yum repo
- yum:
   name: signalfx-agent
   state: present

- name: add signalfx group
   group:
      name: signalfx-agent
      state: present

- name: add signalfx user
   user:
      name: signalfx-agent
      state: present

- name: start signalfx-agent
  service: 
    name: signalfx-agent 
    state: started
    enabled: yes

